name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      
      - name: Generate index file
        run: |
          helm repo index . --url https://edwynrrangel.github.io/charts/

      - name: Get author info
        run: |
          echo "author_name=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV
  
      - name: Print author info
        run: |
          echo "The author name is $author_name"
          echo "The author email is $author_email"
      
      - name: Commit and push changes
        run: |
          git config --local --replace-all user.email "$author_email"
          git config --local --replace-all user.name "$author_name"
          git add index.yaml
          git commit -m "Update chart repository by $author_email" -a || echo "No changes to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/edwynrrangel/charts HEAD:master
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4